// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface ActorCacheOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActorCache)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 role = 3;</code>
   */
  int getRole();

  /**
   * <code>optional string img = 4;</code>
   */
  java.lang.String getImg();
  /**
   * <code>optional string img = 4;</code>
   */
  com.google.protobuf.ByteString
      getImgBytes();

  /**
   * <code>optional int32 type = 5;</code>
   */
  int getType();
}
