// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

/**
 * Protobuf type {@code PicAll}
 */
public  final class PicAll extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PicAll)
    PicAllOrBuilder {
  // Use PicAll.newBuilder() to construct.
  private PicAll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PicAll() {
    picKey_ = "";
    picValue_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PicAll(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            picKey_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            picValue_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.videoservice.VideoServiceProto.internal_static_PicAll_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.videoservice.VideoServiceProto.internal_static_PicAll_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.videoservice.PicAll.class, grpc.videoservice.PicAll.Builder.class);
  }

  public static final int PICKEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object picKey_;
  /**
   * <code>optional string picKey = 1;</code>
   */
  public java.lang.String getPicKey() {
    java.lang.Object ref = picKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      picKey_ = s;
      return s;
    }
  }
  /**
   * <code>optional string picKey = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPicKeyBytes() {
    java.lang.Object ref = picKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      picKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICVALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object picValue_;
  /**
   * <code>optional string picValue = 2;</code>
   */
  public java.lang.String getPicValue() {
    java.lang.Object ref = picValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      picValue_ = s;
      return s;
    }
  }
  /**
   * <code>optional string picValue = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPicValueBytes() {
    java.lang.Object ref = picValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      picValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPicKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, picKey_);
    }
    if (!getPicValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, picValue_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPicKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, picKey_);
    }
    if (!getPicValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, picValue_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.videoservice.PicAll)) {
      return super.equals(obj);
    }
    grpc.videoservice.PicAll other = (grpc.videoservice.PicAll) obj;

    boolean result = true;
    result = result && getPicKey()
        .equals(other.getPicKey());
    result = result && getPicValue()
        .equals(other.getPicValue());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPicKey().hashCode();
    hash = (37 * hash) + PICVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getPicValue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.videoservice.PicAll parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.PicAll parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.PicAll parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.PicAll parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.PicAll parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.PicAll parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.PicAll parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.videoservice.PicAll parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.PicAll parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.PicAll parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.videoservice.PicAll prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PicAll}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PicAll)
      grpc.videoservice.PicAllOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.videoservice.VideoServiceProto.internal_static_PicAll_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.videoservice.VideoServiceProto.internal_static_PicAll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.videoservice.PicAll.class, grpc.videoservice.PicAll.Builder.class);
    }

    // Construct using grpc.videoservice.PicAll.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      picKey_ = "";

      picValue_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.videoservice.VideoServiceProto.internal_static_PicAll_descriptor;
    }

    public grpc.videoservice.PicAll getDefaultInstanceForType() {
      return grpc.videoservice.PicAll.getDefaultInstance();
    }

    public grpc.videoservice.PicAll build() {
      grpc.videoservice.PicAll result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.videoservice.PicAll buildPartial() {
      grpc.videoservice.PicAll result = new grpc.videoservice.PicAll(this);
      result.picKey_ = picKey_;
      result.picValue_ = picValue_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.videoservice.PicAll) {
        return mergeFrom((grpc.videoservice.PicAll)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.videoservice.PicAll other) {
      if (other == grpc.videoservice.PicAll.getDefaultInstance()) return this;
      if (!other.getPicKey().isEmpty()) {
        picKey_ = other.picKey_;
        onChanged();
      }
      if (!other.getPicValue().isEmpty()) {
        picValue_ = other.picValue_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.videoservice.PicAll parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.videoservice.PicAll) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object picKey_ = "";
    /**
     * <code>optional string picKey = 1;</code>
     */
    public java.lang.String getPicKey() {
      java.lang.Object ref = picKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string picKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPicKeyBytes() {
      java.lang.Object ref = picKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string picKey = 1;</code>
     */
    public Builder setPicKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      picKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string picKey = 1;</code>
     */
    public Builder clearPicKey() {
      
      picKey_ = getDefaultInstance().getPicKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string picKey = 1;</code>
     */
    public Builder setPicKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      picKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object picValue_ = "";
    /**
     * <code>optional string picValue = 2;</code>
     */
    public java.lang.String getPicValue() {
      java.lang.Object ref = picValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string picValue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPicValueBytes() {
      java.lang.Object ref = picValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string picValue = 2;</code>
     */
    public Builder setPicValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      picValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string picValue = 2;</code>
     */
    public Builder clearPicValue() {
      
      picValue_ = getDefaultInstance().getPicValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string picValue = 2;</code>
     */
    public Builder setPicValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      picValue_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PicAll)
  }

  // @@protoc_insertion_point(class_scope:PicAll)
  private static final grpc.videoservice.PicAll DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.videoservice.PicAll();
  }

  public static grpc.videoservice.PicAll getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PicAll>
      PARSER = new com.google.protobuf.AbstractParser<PicAll>() {
    public PicAll parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PicAll(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PicAll> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PicAll> getParserForType() {
    return PARSER;
  }

  public grpc.videoservice.PicAll getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

