// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface PicAllOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PicAll)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string picKey = 1;</code>
   */
  java.lang.String getPicKey();
  /**
   * <code>optional string picKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getPicKeyBytes();

  /**
   * <code>optional string picValue = 2;</code>
   */
  java.lang.String getPicValue();
  /**
   * <code>optional string picValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getPicValueBytes();
}
