// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

/**
 * Protobuf type {@code Stream}
 */
public  final class Stream extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Stream)
    StreamOrBuilder {
  // Use Stream.newBuilder() to construct.
  private Stream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stream() {
    name_ = "";
    code_ = "";
    canPlay_ = "";
    canDown_ = "";
    kbps_ = "";
    bandWidth_ = "";
    isDefault_ = false;
    fileSize_ = 0L;
    ifCharge_ = 0;
    liveStreams_ = java.util.Collections.emptyList();
    playStreams_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Stream(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            canPlay_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            canDown_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            kbps_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            bandWidth_ = s;
            break;
          }
          case 56: {

            isDefault_ = input.readBool();
            break;
          }
          case 64: {

            fileSize_ = input.readInt64();
            break;
          }
          case 72: {

            ifCharge_ = input.readInt32();
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              liveStreams_ = new java.util.ArrayList<grpc.videoservice.Stream>();
              mutable_bitField0_ |= 0x00000200;
            }
            liveStreams_.add(
                input.readMessage(grpc.videoservice.Stream.parser(), extensionRegistry));
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              playStreams_ = new java.util.ArrayList<grpc.videoservice.Stream>();
              mutable_bitField0_ |= 0x00000400;
            }
            playStreams_.add(
                input.readMessage(grpc.videoservice.Stream.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        liveStreams_ = java.util.Collections.unmodifiableList(liveStreams_);
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        playStreams_ = java.util.Collections.unmodifiableList(playStreams_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.videoservice.VideoServiceProto.internal_static_Stream_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.videoservice.VideoServiceProto.internal_static_Stream_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.videoservice.Stream.class, grpc.videoservice.Stream.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object code_;
  /**
   * <code>optional string code = 2;</code>
   */
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>optional string code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANPLAY_FIELD_NUMBER = 3;
  private volatile java.lang.Object canPlay_;
  /**
   * <code>optional string canPlay = 3;</code>
   */
  public java.lang.String getCanPlay() {
    java.lang.Object ref = canPlay_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      canPlay_ = s;
      return s;
    }
  }
  /**
   * <code>optional string canPlay = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCanPlayBytes() {
    java.lang.Object ref = canPlay_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      canPlay_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDOWN_FIELD_NUMBER = 4;
  private volatile java.lang.Object canDown_;
  /**
   * <code>optional string canDown = 4;</code>
   */
  public java.lang.String getCanDown() {
    java.lang.Object ref = canDown_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      canDown_ = s;
      return s;
    }
  }
  /**
   * <code>optional string canDown = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCanDownBytes() {
    java.lang.Object ref = canDown_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      canDown_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KBPS_FIELD_NUMBER = 5;
  private volatile java.lang.Object kbps_;
  /**
   * <code>optional string kbps = 5;</code>
   */
  public java.lang.String getKbps() {
    java.lang.Object ref = kbps_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kbps_ = s;
      return s;
    }
  }
  /**
   * <code>optional string kbps = 5;</code>
   */
  public com.google.protobuf.ByteString
      getKbpsBytes() {
    java.lang.Object ref = kbps_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kbps_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANDWIDTH_FIELD_NUMBER = 6;
  private volatile java.lang.Object bandWidth_;
  /**
   * <code>optional string bandWidth = 6;</code>
   */
  public java.lang.String getBandWidth() {
    java.lang.Object ref = bandWidth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bandWidth_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bandWidth = 6;</code>
   */
  public com.google.protobuf.ByteString
      getBandWidthBytes() {
    java.lang.Object ref = bandWidth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bandWidth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISDEFAULT_FIELD_NUMBER = 7;
  private boolean isDefault_;
  /**
   * <code>optional bool isDefault = 7;</code>
   */
  public boolean getIsDefault() {
    return isDefault_;
  }

  public static final int FILESIZE_FIELD_NUMBER = 8;
  private long fileSize_;
  /**
   * <code>optional int64 fileSize = 8;</code>
   */
  public long getFileSize() {
    return fileSize_;
  }

  public static final int IFCHARGE_FIELD_NUMBER = 9;
  private int ifCharge_;
  /**
   * <code>optional int32 ifCharge = 9;</code>
   */
  public int getIfCharge() {
    return ifCharge_;
  }

  public static final int LIVESTREAMS_FIELD_NUMBER = 10;
  private java.util.List<grpc.videoservice.Stream> liveStreams_;
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  public java.util.List<grpc.videoservice.Stream> getLiveStreamsList() {
    return liveStreams_;
  }
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  public java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getLiveStreamsOrBuilderList() {
    return liveStreams_;
  }
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  public int getLiveStreamsCount() {
    return liveStreams_.size();
  }
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  public grpc.videoservice.Stream getLiveStreams(int index) {
    return liveStreams_.get(index);
  }
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  public grpc.videoservice.StreamOrBuilder getLiveStreamsOrBuilder(
      int index) {
    return liveStreams_.get(index);
  }

  public static final int PLAYSTREAMS_FIELD_NUMBER = 11;
  private java.util.List<grpc.videoservice.Stream> playStreams_;
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  public java.util.List<grpc.videoservice.Stream> getPlayStreamsList() {
    return playStreams_;
  }
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  public java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getPlayStreamsOrBuilderList() {
    return playStreams_;
  }
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  public int getPlayStreamsCount() {
    return playStreams_.size();
  }
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  public grpc.videoservice.Stream getPlayStreams(int index) {
    return playStreams_.get(index);
  }
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  public grpc.videoservice.StreamOrBuilder getPlayStreamsOrBuilder(
      int index) {
    return playStreams_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    if (!getCanPlayBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, canPlay_);
    }
    if (!getCanDownBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, canDown_);
    }
    if (!getKbpsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, kbps_);
    }
    if (!getBandWidthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bandWidth_);
    }
    if (isDefault_ != false) {
      output.writeBool(7, isDefault_);
    }
    if (fileSize_ != 0L) {
      output.writeInt64(8, fileSize_);
    }
    if (ifCharge_ != 0) {
      output.writeInt32(9, ifCharge_);
    }
    for (int i = 0; i < liveStreams_.size(); i++) {
      output.writeMessage(10, liveStreams_.get(i));
    }
    for (int i = 0; i < playStreams_.size(); i++) {
      output.writeMessage(11, playStreams_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    if (!getCanPlayBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, canPlay_);
    }
    if (!getCanDownBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, canDown_);
    }
    if (!getKbpsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, kbps_);
    }
    if (!getBandWidthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bandWidth_);
    }
    if (isDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isDefault_);
    }
    if (fileSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, fileSize_);
    }
    if (ifCharge_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, ifCharge_);
    }
    for (int i = 0; i < liveStreams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, liveStreams_.get(i));
    }
    for (int i = 0; i < playStreams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, playStreams_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.videoservice.Stream)) {
      return super.equals(obj);
    }
    grpc.videoservice.Stream other = (grpc.videoservice.Stream) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getCode()
        .equals(other.getCode());
    result = result && getCanPlay()
        .equals(other.getCanPlay());
    result = result && getCanDown()
        .equals(other.getCanDown());
    result = result && getKbps()
        .equals(other.getKbps());
    result = result && getBandWidth()
        .equals(other.getBandWidth());
    result = result && (getIsDefault()
        == other.getIsDefault());
    result = result && (getFileSize()
        == other.getFileSize());
    result = result && (getIfCharge()
        == other.getIfCharge());
    result = result && getLiveStreamsList()
        .equals(other.getLiveStreamsList());
    result = result && getPlayStreamsList()
        .equals(other.getPlayStreamsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + CANPLAY_FIELD_NUMBER;
    hash = (53 * hash) + getCanPlay().hashCode();
    hash = (37 * hash) + CANDOWN_FIELD_NUMBER;
    hash = (53 * hash) + getCanDown().hashCode();
    hash = (37 * hash) + KBPS_FIELD_NUMBER;
    hash = (53 * hash) + getKbps().hashCode();
    hash = (37 * hash) + BANDWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getBandWidth().hashCode();
    hash = (37 * hash) + ISDEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDefault());
    hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFileSize());
    hash = (37 * hash) + IFCHARGE_FIELD_NUMBER;
    hash = (53 * hash) + getIfCharge();
    if (getLiveStreamsCount() > 0) {
      hash = (37 * hash) + LIVESTREAMS_FIELD_NUMBER;
      hash = (53 * hash) + getLiveStreamsList().hashCode();
    }
    if (getPlayStreamsCount() > 0) {
      hash = (37 * hash) + PLAYSTREAMS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayStreamsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.videoservice.Stream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.Stream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.Stream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.Stream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.Stream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Stream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.Stream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Stream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.Stream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Stream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.videoservice.Stream prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Stream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Stream)
      grpc.videoservice.StreamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.videoservice.VideoServiceProto.internal_static_Stream_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.videoservice.VideoServiceProto.internal_static_Stream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.videoservice.Stream.class, grpc.videoservice.Stream.Builder.class);
    }

    // Construct using grpc.videoservice.Stream.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLiveStreamsFieldBuilder();
        getPlayStreamsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      code_ = "";

      canPlay_ = "";

      canDown_ = "";

      kbps_ = "";

      bandWidth_ = "";

      isDefault_ = false;

      fileSize_ = 0L;

      ifCharge_ = 0;

      if (liveStreamsBuilder_ == null) {
        liveStreams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        liveStreamsBuilder_.clear();
      }
      if (playStreamsBuilder_ == null) {
        playStreams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
      } else {
        playStreamsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.videoservice.VideoServiceProto.internal_static_Stream_descriptor;
    }

    public grpc.videoservice.Stream getDefaultInstanceForType() {
      return grpc.videoservice.Stream.getDefaultInstance();
    }

    public grpc.videoservice.Stream build() {
      grpc.videoservice.Stream result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.videoservice.Stream buildPartial() {
      grpc.videoservice.Stream result = new grpc.videoservice.Stream(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.code_ = code_;
      result.canPlay_ = canPlay_;
      result.canDown_ = canDown_;
      result.kbps_ = kbps_;
      result.bandWidth_ = bandWidth_;
      result.isDefault_ = isDefault_;
      result.fileSize_ = fileSize_;
      result.ifCharge_ = ifCharge_;
      if (liveStreamsBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          liveStreams_ = java.util.Collections.unmodifiableList(liveStreams_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.liveStreams_ = liveStreams_;
      } else {
        result.liveStreams_ = liveStreamsBuilder_.build();
      }
      if (playStreamsBuilder_ == null) {
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          playStreams_ = java.util.Collections.unmodifiableList(playStreams_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.playStreams_ = playStreams_;
      } else {
        result.playStreams_ = playStreamsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.videoservice.Stream) {
        return mergeFrom((grpc.videoservice.Stream)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.videoservice.Stream other) {
      if (other == grpc.videoservice.Stream.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (!other.getCanPlay().isEmpty()) {
        canPlay_ = other.canPlay_;
        onChanged();
      }
      if (!other.getCanDown().isEmpty()) {
        canDown_ = other.canDown_;
        onChanged();
      }
      if (!other.getKbps().isEmpty()) {
        kbps_ = other.kbps_;
        onChanged();
      }
      if (!other.getBandWidth().isEmpty()) {
        bandWidth_ = other.bandWidth_;
        onChanged();
      }
      if (other.getIsDefault() != false) {
        setIsDefault(other.getIsDefault());
      }
      if (other.getFileSize() != 0L) {
        setFileSize(other.getFileSize());
      }
      if (other.getIfCharge() != 0) {
        setIfCharge(other.getIfCharge());
      }
      if (liveStreamsBuilder_ == null) {
        if (!other.liveStreams_.isEmpty()) {
          if (liveStreams_.isEmpty()) {
            liveStreams_ = other.liveStreams_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureLiveStreamsIsMutable();
            liveStreams_.addAll(other.liveStreams_);
          }
          onChanged();
        }
      } else {
        if (!other.liveStreams_.isEmpty()) {
          if (liveStreamsBuilder_.isEmpty()) {
            liveStreamsBuilder_.dispose();
            liveStreamsBuilder_ = null;
            liveStreams_ = other.liveStreams_;
            bitField0_ = (bitField0_ & ~0x00000200);
            liveStreamsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLiveStreamsFieldBuilder() : null;
          } else {
            liveStreamsBuilder_.addAllMessages(other.liveStreams_);
          }
        }
      }
      if (playStreamsBuilder_ == null) {
        if (!other.playStreams_.isEmpty()) {
          if (playStreams_.isEmpty()) {
            playStreams_ = other.playStreams_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensurePlayStreamsIsMutable();
            playStreams_.addAll(other.playStreams_);
          }
          onChanged();
        }
      } else {
        if (!other.playStreams_.isEmpty()) {
          if (playStreamsBuilder_.isEmpty()) {
            playStreamsBuilder_.dispose();
            playStreamsBuilder_ = null;
            playStreams_ = other.playStreams_;
            bitField0_ = (bitField0_ & ~0x00000400);
            playStreamsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayStreamsFieldBuilder() : null;
          } else {
            playStreamsBuilder_.addAllMessages(other.playStreams_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.videoservice.Stream parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.videoservice.Stream) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>optional string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object canPlay_ = "";
    /**
     * <code>optional string canPlay = 3;</code>
     */
    public java.lang.String getCanPlay() {
      java.lang.Object ref = canPlay_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        canPlay_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string canPlay = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCanPlayBytes() {
      java.lang.Object ref = canPlay_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        canPlay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string canPlay = 3;</code>
     */
    public Builder setCanPlay(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      canPlay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string canPlay = 3;</code>
     */
    public Builder clearCanPlay() {
      
      canPlay_ = getDefaultInstance().getCanPlay();
      onChanged();
      return this;
    }
    /**
     * <code>optional string canPlay = 3;</code>
     */
    public Builder setCanPlayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      canPlay_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object canDown_ = "";
    /**
     * <code>optional string canDown = 4;</code>
     */
    public java.lang.String getCanDown() {
      java.lang.Object ref = canDown_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        canDown_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string canDown = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCanDownBytes() {
      java.lang.Object ref = canDown_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        canDown_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string canDown = 4;</code>
     */
    public Builder setCanDown(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      canDown_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string canDown = 4;</code>
     */
    public Builder clearCanDown() {
      
      canDown_ = getDefaultInstance().getCanDown();
      onChanged();
      return this;
    }
    /**
     * <code>optional string canDown = 4;</code>
     */
    public Builder setCanDownBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      canDown_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object kbps_ = "";
    /**
     * <code>optional string kbps = 5;</code>
     */
    public java.lang.String getKbps() {
      java.lang.Object ref = kbps_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kbps_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string kbps = 5;</code>
     */
    public com.google.protobuf.ByteString
        getKbpsBytes() {
      java.lang.Object ref = kbps_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kbps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string kbps = 5;</code>
     */
    public Builder setKbps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      kbps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string kbps = 5;</code>
     */
    public Builder clearKbps() {
      
      kbps_ = getDefaultInstance().getKbps();
      onChanged();
      return this;
    }
    /**
     * <code>optional string kbps = 5;</code>
     */
    public Builder setKbpsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      kbps_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bandWidth_ = "";
    /**
     * <code>optional string bandWidth = 6;</code>
     */
    public java.lang.String getBandWidth() {
      java.lang.Object ref = bandWidth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bandWidth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string bandWidth = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBandWidthBytes() {
      java.lang.Object ref = bandWidth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bandWidth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bandWidth = 6;</code>
     */
    public Builder setBandWidth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bandWidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bandWidth = 6;</code>
     */
    public Builder clearBandWidth() {
      
      bandWidth_ = getDefaultInstance().getBandWidth();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bandWidth = 6;</code>
     */
    public Builder setBandWidthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bandWidth_ = value;
      onChanged();
      return this;
    }

    private boolean isDefault_ ;
    /**
     * <code>optional bool isDefault = 7;</code>
     */
    public boolean getIsDefault() {
      return isDefault_;
    }
    /**
     * <code>optional bool isDefault = 7;</code>
     */
    public Builder setIsDefault(boolean value) {
      
      isDefault_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isDefault = 7;</code>
     */
    public Builder clearIsDefault() {
      
      isDefault_ = false;
      onChanged();
      return this;
    }

    private long fileSize_ ;
    /**
     * <code>optional int64 fileSize = 8;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <code>optional int64 fileSize = 8;</code>
     */
    public Builder setFileSize(long value) {
      
      fileSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 fileSize = 8;</code>
     */
    public Builder clearFileSize() {
      
      fileSize_ = 0L;
      onChanged();
      return this;
    }

    private int ifCharge_ ;
    /**
     * <code>optional int32 ifCharge = 9;</code>
     */
    public int getIfCharge() {
      return ifCharge_;
    }
    /**
     * <code>optional int32 ifCharge = 9;</code>
     */
    public Builder setIfCharge(int value) {
      
      ifCharge_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 ifCharge = 9;</code>
     */
    public Builder clearIfCharge() {
      
      ifCharge_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<grpc.videoservice.Stream> liveStreams_ =
      java.util.Collections.emptyList();
    private void ensureLiveStreamsIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        liveStreams_ = new java.util.ArrayList<grpc.videoservice.Stream>(liveStreams_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder> liveStreamsBuilder_;

    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public java.util.List<grpc.videoservice.Stream> getLiveStreamsList() {
      if (liveStreamsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(liveStreams_);
      } else {
        return liveStreamsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public int getLiveStreamsCount() {
      if (liveStreamsBuilder_ == null) {
        return liveStreams_.size();
      } else {
        return liveStreamsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public grpc.videoservice.Stream getLiveStreams(int index) {
      if (liveStreamsBuilder_ == null) {
        return liveStreams_.get(index);
      } else {
        return liveStreamsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder setLiveStreams(
        int index, grpc.videoservice.Stream value) {
      if (liveStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLiveStreamsIsMutable();
        liveStreams_.set(index, value);
        onChanged();
      } else {
        liveStreamsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder setLiveStreams(
        int index, grpc.videoservice.Stream.Builder builderForValue) {
      if (liveStreamsBuilder_ == null) {
        ensureLiveStreamsIsMutable();
        liveStreams_.set(index, builderForValue.build());
        onChanged();
      } else {
        liveStreamsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder addLiveStreams(grpc.videoservice.Stream value) {
      if (liveStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLiveStreamsIsMutable();
        liveStreams_.add(value);
        onChanged();
      } else {
        liveStreamsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder addLiveStreams(
        int index, grpc.videoservice.Stream value) {
      if (liveStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLiveStreamsIsMutable();
        liveStreams_.add(index, value);
        onChanged();
      } else {
        liveStreamsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder addLiveStreams(
        grpc.videoservice.Stream.Builder builderForValue) {
      if (liveStreamsBuilder_ == null) {
        ensureLiveStreamsIsMutable();
        liveStreams_.add(builderForValue.build());
        onChanged();
      } else {
        liveStreamsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder addLiveStreams(
        int index, grpc.videoservice.Stream.Builder builderForValue) {
      if (liveStreamsBuilder_ == null) {
        ensureLiveStreamsIsMutable();
        liveStreams_.add(index, builderForValue.build());
        onChanged();
      } else {
        liveStreamsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder addAllLiveStreams(
        java.lang.Iterable<? extends grpc.videoservice.Stream> values) {
      if (liveStreamsBuilder_ == null) {
        ensureLiveStreamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, liveStreams_);
        onChanged();
      } else {
        liveStreamsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder clearLiveStreams() {
      if (liveStreamsBuilder_ == null) {
        liveStreams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        liveStreamsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public Builder removeLiveStreams(int index) {
      if (liveStreamsBuilder_ == null) {
        ensureLiveStreamsIsMutable();
        liveStreams_.remove(index);
        onChanged();
      } else {
        liveStreamsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public grpc.videoservice.Stream.Builder getLiveStreamsBuilder(
        int index) {
      return getLiveStreamsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public grpc.videoservice.StreamOrBuilder getLiveStreamsOrBuilder(
        int index) {
      if (liveStreamsBuilder_ == null) {
        return liveStreams_.get(index);  } else {
        return liveStreamsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
         getLiveStreamsOrBuilderList() {
      if (liveStreamsBuilder_ != null) {
        return liveStreamsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(liveStreams_);
      }
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public grpc.videoservice.Stream.Builder addLiveStreamsBuilder() {
      return getLiveStreamsFieldBuilder().addBuilder(
          grpc.videoservice.Stream.getDefaultInstance());
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public grpc.videoservice.Stream.Builder addLiveStreamsBuilder(
        int index) {
      return getLiveStreamsFieldBuilder().addBuilder(
          index, grpc.videoservice.Stream.getDefaultInstance());
    }
    /**
     * <code>repeated .Stream liveStreams = 10;</code>
     */
    public java.util.List<grpc.videoservice.Stream.Builder> 
         getLiveStreamsBuilderList() {
      return getLiveStreamsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder> 
        getLiveStreamsFieldBuilder() {
      if (liveStreamsBuilder_ == null) {
        liveStreamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder>(
                liveStreams_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        liveStreams_ = null;
      }
      return liveStreamsBuilder_;
    }

    private java.util.List<grpc.videoservice.Stream> playStreams_ =
      java.util.Collections.emptyList();
    private void ensurePlayStreamsIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        playStreams_ = new java.util.ArrayList<grpc.videoservice.Stream>(playStreams_);
        bitField0_ |= 0x00000400;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder> playStreamsBuilder_;

    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public java.util.List<grpc.videoservice.Stream> getPlayStreamsList() {
      if (playStreamsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(playStreams_);
      } else {
        return playStreamsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public int getPlayStreamsCount() {
      if (playStreamsBuilder_ == null) {
        return playStreams_.size();
      } else {
        return playStreamsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public grpc.videoservice.Stream getPlayStreams(int index) {
      if (playStreamsBuilder_ == null) {
        return playStreams_.get(index);
      } else {
        return playStreamsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder setPlayStreams(
        int index, grpc.videoservice.Stream value) {
      if (playStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayStreamsIsMutable();
        playStreams_.set(index, value);
        onChanged();
      } else {
        playStreamsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder setPlayStreams(
        int index, grpc.videoservice.Stream.Builder builderForValue) {
      if (playStreamsBuilder_ == null) {
        ensurePlayStreamsIsMutable();
        playStreams_.set(index, builderForValue.build());
        onChanged();
      } else {
        playStreamsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder addPlayStreams(grpc.videoservice.Stream value) {
      if (playStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayStreamsIsMutable();
        playStreams_.add(value);
        onChanged();
      } else {
        playStreamsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder addPlayStreams(
        int index, grpc.videoservice.Stream value) {
      if (playStreamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayStreamsIsMutable();
        playStreams_.add(index, value);
        onChanged();
      } else {
        playStreamsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder addPlayStreams(
        grpc.videoservice.Stream.Builder builderForValue) {
      if (playStreamsBuilder_ == null) {
        ensurePlayStreamsIsMutable();
        playStreams_.add(builderForValue.build());
        onChanged();
      } else {
        playStreamsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder addPlayStreams(
        int index, grpc.videoservice.Stream.Builder builderForValue) {
      if (playStreamsBuilder_ == null) {
        ensurePlayStreamsIsMutable();
        playStreams_.add(index, builderForValue.build());
        onChanged();
      } else {
        playStreamsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder addAllPlayStreams(
        java.lang.Iterable<? extends grpc.videoservice.Stream> values) {
      if (playStreamsBuilder_ == null) {
        ensurePlayStreamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, playStreams_);
        onChanged();
      } else {
        playStreamsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder clearPlayStreams() {
      if (playStreamsBuilder_ == null) {
        playStreams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
      } else {
        playStreamsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public Builder removePlayStreams(int index) {
      if (playStreamsBuilder_ == null) {
        ensurePlayStreamsIsMutable();
        playStreams_.remove(index);
        onChanged();
      } else {
        playStreamsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public grpc.videoservice.Stream.Builder getPlayStreamsBuilder(
        int index) {
      return getPlayStreamsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public grpc.videoservice.StreamOrBuilder getPlayStreamsOrBuilder(
        int index) {
      if (playStreamsBuilder_ == null) {
        return playStreams_.get(index);  } else {
        return playStreamsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
         getPlayStreamsOrBuilderList() {
      if (playStreamsBuilder_ != null) {
        return playStreamsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(playStreams_);
      }
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public grpc.videoservice.Stream.Builder addPlayStreamsBuilder() {
      return getPlayStreamsFieldBuilder().addBuilder(
          grpc.videoservice.Stream.getDefaultInstance());
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public grpc.videoservice.Stream.Builder addPlayStreamsBuilder(
        int index) {
      return getPlayStreamsFieldBuilder().addBuilder(
          index, grpc.videoservice.Stream.getDefaultInstance());
    }
    /**
     * <code>repeated .Stream playStreams = 11;</code>
     */
    public java.util.List<grpc.videoservice.Stream.Builder> 
         getPlayStreamsBuilderList() {
      return getPlayStreamsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder> 
        getPlayStreamsFieldBuilder() {
      if (playStreamsBuilder_ == null) {
        playStreamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.videoservice.Stream, grpc.videoservice.Stream.Builder, grpc.videoservice.StreamOrBuilder>(
                playStreams_,
                ((bitField0_ & 0x00000400) == 0x00000400),
                getParentForChildren(),
                isClean());
        playStreams_ = null;
      }
      return playStreamsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Stream)
  }

  // @@protoc_insertion_point(class_scope:Stream)
  private static final grpc.videoservice.Stream DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.videoservice.Stream();
  }

  public static grpc.videoservice.Stream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stream>
      PARSER = new com.google.protobuf.AbstractParser<Stream>() {
    public Stream parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stream(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Stream> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stream> getParserForType() {
    return PARSER;
  }

  public grpc.videoservice.Stream getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

