// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface StreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Stream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string canPlay = 3;</code>
   */
  java.lang.String getCanPlay();
  /**
   * <code>optional string canPlay = 3;</code>
   */
  com.google.protobuf.ByteString
      getCanPlayBytes();

  /**
   * <code>optional string canDown = 4;</code>
   */
  java.lang.String getCanDown();
  /**
   * <code>optional string canDown = 4;</code>
   */
  com.google.protobuf.ByteString
      getCanDownBytes();

  /**
   * <code>optional string kbps = 5;</code>
   */
  java.lang.String getKbps();
  /**
   * <code>optional string kbps = 5;</code>
   */
  com.google.protobuf.ByteString
      getKbpsBytes();

  /**
   * <code>optional string bandWidth = 6;</code>
   */
  java.lang.String getBandWidth();
  /**
   * <code>optional string bandWidth = 6;</code>
   */
  com.google.protobuf.ByteString
      getBandWidthBytes();

  /**
   * <code>optional bool isDefault = 7;</code>
   */
  boolean getIsDefault();

  /**
   * <code>optional int64 fileSize = 8;</code>
   */
  long getFileSize();

  /**
   * <code>optional int32 ifCharge = 9;</code>
   */
  int getIfCharge();

  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getLiveStreamsList();
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  grpc.videoservice.Stream getLiveStreams(int index);
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  int getLiveStreamsCount();
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getLiveStreamsOrBuilderList();
  /**
   * <code>repeated .Stream liveStreams = 10;</code>
   */
  grpc.videoservice.StreamOrBuilder getLiveStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getPlayStreamsList();
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  grpc.videoservice.Stream getPlayStreams(int index);
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  int getPlayStreamsCount();
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getPlayStreamsOrBuilderList();
  /**
   * <code>repeated .Stream playStreams = 11;</code>
   */
  grpc.videoservice.StreamOrBuilder getPlayStreamsOrBuilder(
      int index);
}
