// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 albumId = 1;</code>
   */
  long getAlbumId();

  /**
   * <code>optional int64 id = 2;</code>
   */
  long getId();

  /**
   * <code>optional int32 type = 3;</code>
   */
  int getType();

  /**
   * <code>optional int32 porder = 4;</code>
   */
  int getPorder();

  /**
   * <code>optional string mid = 5;</code>
   */
  java.lang.String getMid();
  /**
   * <code>optional string mid = 5;</code>
   */
  com.google.protobuf.ByteString
      getMidBytes();

  /**
   * <code>optional string nameCn = 6;</code>
   */
  java.lang.String getNameCn();
  /**
   * <code>optional string nameCn = 6;</code>
   */
  com.google.protobuf.ByteString
      getNameCnBytes();

  /**
   * <code>optional string alias = 7;</code>
   */
  java.lang.String getAlias();
  /**
   * <code>optional string alias = 7;</code>
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>optional string subTitle = 8;</code>
   */
  java.lang.String getSubTitle();
  /**
   * <code>optional string subTitle = 8;</code>
   */
  com.google.protobuf.ByteString
      getSubTitleBytes();

  /**
   * <code>optional string shortDesc = 9;</code>
   */
  java.lang.String getShortDesc();
  /**
   * <code>optional string shortDesc = 9;</code>
   */
  com.google.protobuf.ByteString
      getShortDescBytes();

  /**
   * <code>optional string description = 10;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 10;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional string tag = 11;</code>
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 11;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional int32 categoryId = 12;</code>
   */
  int getCategoryId();

  /**
   * <code>optional string categoryName = 13;</code>
   */
  java.lang.String getCategoryName();
  /**
   * <code>optional string categoryName = 13;</code>
   */
  com.google.protobuf.ByteString
      getCategoryNameBytes();

  /**
   * <code>optional string subCategory = 14;</code>
   */
  java.lang.String getSubCategory();
  /**
   * <code>optional string subCategory = 14;</code>
   */
  com.google.protobuf.ByteString
      getSubCategoryBytes();

  /**
   * <code>optional string subCategoryName = 15;</code>
   */
  java.lang.String getSubCategoryName();
  /**
   * <code>optional string subCategoryName = 15;</code>
   */
  com.google.protobuf.ByteString
      getSubCategoryNameBytes();

  /**
   * <code>optional string area = 16;</code>
   */
  java.lang.String getArea();
  /**
   * <code>optional string area = 16;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>optional string areaName = 17;</code>
   */
  java.lang.String getAreaName();
  /**
   * <code>optional string areaName = 17;</code>
   */
  com.google.protobuf.ByteString
      getAreaNameBytes();

  /**
   * <code>optional string episode = 18;</code>
   */
  java.lang.String getEpisode();
  /**
   * <code>optional string episode = 18;</code>
   */
  com.google.protobuf.ByteString
      getEpisodeBytes();

  /**
   * <code>optional int32 btime = 19;</code>
   */
  int getBtime();

  /**
   * <code>optional int32 etime = 20;</code>
   */
  int getEtime();

  /**
   * <code>repeated .WatchingFocusCache watchingFocus = 21;</code>
   */
  java.util.List<grpc.videoservice.WatchingFocusCache> 
      getWatchingFocusList();
  /**
   * <code>repeated .WatchingFocusCache watchingFocus = 21;</code>
   */
  grpc.videoservice.WatchingFocusCache getWatchingFocus(int index);
  /**
   * <code>repeated .WatchingFocusCache watchingFocus = 21;</code>
   */
  int getWatchingFocusCount();
  /**
   * <code>repeated .WatchingFocusCache watchingFocus = 21;</code>
   */
  java.util.List<? extends grpc.videoservice.WatchingFocusCacheOrBuilder> 
      getWatchingFocusOrBuilderList();
  /**
   * <code>repeated .WatchingFocusCache watchingFocus = 21;</code>
   */
  grpc.videoservice.WatchingFocusCacheOrBuilder getWatchingFocusOrBuilder(
      int index);

  /**
   * <code>optional string downloadPlatform = 22;</code>
   */
  java.lang.String getDownloadPlatform();
  /**
   * <code>optional string downloadPlatform = 22;</code>
   */
  com.google.protobuf.ByteString
      getDownloadPlatformBytes();

  /**
   * <code>optional string playPlatform = 23;</code>
   */
  java.lang.String getPlayPlatform();
  /**
   * <code>optional string playPlatform = 23;</code>
   */
  com.google.protobuf.ByteString
      getPlayPlatformBytes();

  /**
   * <code>optional string payPlatform = 24;</code>
   */
  java.lang.String getPayPlatform();
  /**
   * <code>optional string payPlatform = 24;</code>
   */
  com.google.protobuf.ByteString
      getPayPlatformBytes();

  /**
   * <code>optional int32 duration = 25;</code>
   */
  int getDuration();

  /**
   * <code>optional int32 status = 26;</code>
   */
  int getStatus();

  /**
   * <code>optional int32 deleted = 27;</code>
   */
  int getDeleted();

  /**
   * <code>optional string remark = 28;</code>
   */
  java.lang.String getRemark();
  /**
   * <code>optional string remark = 28;</code>
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <code>optional float score = 29;</code>
   */
  float getScore();

  /**
   * <code>repeated .PicAll picAll = 30;</code>
   */
  java.util.List<grpc.videoservice.PicAll> 
      getPicAllList();
  /**
   * <code>repeated .PicAll picAll = 30;</code>
   */
  grpc.videoservice.PicAll getPicAll(int index);
  /**
   * <code>repeated .PicAll picAll = 30;</code>
   */
  int getPicAllCount();
  /**
   * <code>repeated .PicAll picAll = 30;</code>
   */
  java.util.List<? extends grpc.videoservice.PicAllOrBuilder> 
      getPicAllOrBuilderList();
  /**
   * <code>repeated .PicAll picAll = 30;</code>
   */
  grpc.videoservice.PicAllOrBuilder getPicAllOrBuilder(
      int index);

  /**
   * <code>optional string picOriginal = 31;</code>
   */
  java.lang.String getPicOriginal();
  /**
   * <code>optional string picOriginal = 31;</code>
   */
  com.google.protobuf.ByteString
      getPicOriginalBytes();

  /**
   * <code>optional string relativeContent = 32;</code>
   */
  java.lang.String getRelativeContent();
  /**
   * <code>optional string relativeContent = 32;</code>
   */
  com.google.protobuf.ByteString
      getRelativeContentBytes();

  /**
   * <code>optional string releaseDate = 33;</code>
   */
  java.lang.String getReleaseDate();
  /**
   * <code>optional string releaseDate = 33;</code>
   */
  com.google.protobuf.ByteString
      getReleaseDateBytes();

  /**
   * <code>optional string firstPlayTime = 34;</code>
   */
  java.lang.String getFirstPlayTime();
  /**
   * <code>optional string firstPlayTime = 34;</code>
   */
  com.google.protobuf.ByteString
      getFirstPlayTimeBytes();

  /**
   * <code>optional int32 issue = 35;</code>
   */
  int getIssue();

  /**
   * <code>optional string school = 36;</code>
   */
  java.lang.String getSchool();
  /**
   * <code>optional string school = 36;</code>
   */
  com.google.protobuf.ByteString
      getSchoolBytes();

  /**
   * <code>optional string starring = 37;</code>
   */
  java.lang.String getStarring();
  /**
   * <code>optional string starring = 37;</code>
   */
  com.google.protobuf.ByteString
      getStarringBytes();

  /**
   * <code>optional string directory = 38;</code>
   */
  java.lang.String getDirectory();
  /**
   * <code>optional string directory = 38;</code>
   */
  com.google.protobuf.ByteString
      getDirectoryBytes();

  /**
   * <code>optional string actor = 39;</code>
   */
  java.lang.String getActor();
  /**
   * <code>optional string actor = 39;</code>
   */
  com.google.protobuf.ByteString
      getActorBytes();

  /**
   * <code>optional string actorPlay = 40;</code>
   */
  java.lang.String getActorPlay();
  /**
   * <code>optional string actorPlay = 40;</code>
   */
  com.google.protobuf.ByteString
      getActorPlayBytes();

  /**
   * <code>optional int32 language = 41;</code>
   */
  int getLanguage();

  /**
   * <code>optional string languageName = 42;</code>
   */
  java.lang.String getLanguageName();
  /**
   * <code>optional string languageName = 42;</code>
   */
  com.google.protobuf.ByteString
      getLanguageNameBytes();

  /**
   * <code>optional string singleName = 43;</code>
   */
  java.lang.String getSingleName();
  /**
   * <code>optional string singleName = 43;</code>
   */
  com.google.protobuf.ByteString
      getSingleNameBytes();

  /**
   * <code>optional int32 style = 44;</code>
   */
  int getStyle();

  /**
   * <code>optional string styleName = 45;</code>
   */
  java.lang.String getStyleName();
  /**
   * <code>optional string styleName = 45;</code>
   */
  com.google.protobuf.ByteString
      getStyleNameBytes();

  /**
   * <code>optional int32 sportsType = 46;</code>
   */
  int getSportsType();

  /**
   * <code>optional string sportsTypeName = 47;</code>
   */
  java.lang.String getSportsTypeName();
  /**
   * <code>optional string sportsTypeName = 47;</code>
   */
  com.google.protobuf.ByteString
      getSportsTypeNameBytes();

  /**
   * <code>optional int32 letvMakeStyle = 48;</code>
   */
  int getLetvMakeStyle();

  /**
   * <code>optional string letvMakeStyleName = 49;</code>
   */
  java.lang.String getLetvMakeStyleName();
  /**
   * <code>optional string letvMakeStyleName = 49;</code>
   */
  com.google.protobuf.ByteString
      getLetvMakeStyleNameBytes();

  /**
   * <code>optional int32 popStyle = 50;</code>
   */
  int getPopStyle();

  /**
   * <code>optional string popStyleName = 51;</code>
   */
  java.lang.String getPopStyleName();
  /**
   * <code>optional string popStyleName = 51;</code>
   */
  com.google.protobuf.ByteString
      getPopStyleNameBytes();

  /**
   * <code>optional int32 letvProduceStyle = 52;</code>
   */
  int getLetvProduceStyle();

  /**
   * <code>optional string letvProduceStyleName = 53;</code>
   */
  java.lang.String getLetvProduceStyleName();
  /**
   * <code>optional string letvProduceStyleName = 53;</code>
   */
  com.google.protobuf.ByteString
      getLetvProduceStyleNameBytes();

  /**
   * <code>optional string cartoonStyle = 54;</code>
   */
  java.lang.String getCartoonStyle();
  /**
   * <code>optional string cartoonStyle = 54;</code>
   */
  com.google.protobuf.ByteString
      getCartoonStyleBytes();

  /**
   * <code>optional string cartoonStyleName = 55;</code>
   */
  java.lang.String getCartoonStyleName();
  /**
   * <code>optional string cartoonStyleName = 55;</code>
   */
  com.google.protobuf.ByteString
      getCartoonStyleNameBytes();

  /**
   * <code>optional int32 fieldType = 56;</code>
   */
  int getFieldType();

  /**
   * <code>optional string fieldTypeName = 57;</code>
   */
  java.lang.String getFieldTypeName();
  /**
   * <code>optional string fieldTypeName = 57;</code>
   */
  com.google.protobuf.ByteString
      getFieldTypeNameBytes();

  /**
   * <code>optional int32 pre = 58;</code>
   */
  int getPre();

  /**
   * <code>optional string preName = 59;</code>
   */
  java.lang.String getPreName();
  /**
   * <code>optional string preName = 59;</code>
   */
  com.google.protobuf.ByteString
      getPreNameBytes();

  /**
   * <code>optional string instructor = 60;</code>
   */
  java.lang.String getInstructor();
  /**
   * <code>optional string instructor = 60;</code>
   */
  com.google.protobuf.ByteString
      getInstructorBytes();

  /**
   * <code>optional string compere = 61;</code>
   */
  java.lang.String getCompere();
  /**
   * <code>optional string compere = 61;</code>
   */
  com.google.protobuf.ByteString
      getCompereBytes();

  /**
   * <code>optional string guest = 62;</code>
   */
  java.lang.String getGuest();
  /**
   * <code>optional string guest = 62;</code>
   */
  com.google.protobuf.ByteString
      getGuestBytes();

  /**
   * <code>optional string singer = 63;</code>
   */
  java.lang.String getSinger();
  /**
   * <code>optional string singer = 63;</code>
   */
  com.google.protobuf.ByteString
      getSingerBytes();

  /**
   * <code>optional string singerType = 64;</code>
   */
  java.lang.String getSingerType();
  /**
   * <code>optional string singerType = 64;</code>
   */
  com.google.protobuf.ByteString
      getSingerTypeBytes();

  /**
   * <code>optional string singerTypeName = 65;</code>
   */
  java.lang.String getSingerTypeName();
  /**
   * <code>optional string singerTypeName = 65;</code>
   */
  com.google.protobuf.ByteString
      getSingerTypeNameBytes();

  /**
   * <code>optional string musicAuthors = 66;</code>
   */
  java.lang.String getMusicAuthors();
  /**
   * <code>optional string musicAuthors = 66;</code>
   */
  com.google.protobuf.ByteString
      getMusicAuthorsBytes();

  /**
   * <code>optional string musicStyle = 67;</code>
   */
  java.lang.String getMusicStyle();
  /**
   * <code>optional string musicStyle = 67;</code>
   */
  com.google.protobuf.ByteString
      getMusicStyleBytes();

  /**
   * <code>optional string musicStyleName = 68;</code>
   */
  java.lang.String getMusicStyleName();
  /**
   * <code>optional string musicStyleName = 68;</code>
   */
  com.google.protobuf.ByteString
      getMusicStyleNameBytes();

  /**
   * <code>optional int32 travelTheme = 69;</code>
   */
  int getTravelTheme();

  /**
   * <code>optional string travelThemeName = 70;</code>
   */
  java.lang.String getTravelThemeName();
  /**
   * <code>optional string travelThemeName = 70;</code>
   */
  com.google.protobuf.ByteString
      getTravelThemeNameBytes();

  /**
   * <code>optional int32 travelType = 71;</code>
   */
  int getTravelType();

  /**
   * <code>optional string travelTypeName = 72;</code>
   */
  java.lang.String getTravelTypeName();
  /**
   * <code>optional string travelTypeName = 72;</code>
   */
  com.google.protobuf.ByteString
      getTravelTypeNameBytes();

  /**
   * <code>optional string maker = 73;</code>
   */
  java.lang.String getMaker();
  /**
   * <code>optional string maker = 73;</code>
   */
  com.google.protobuf.ByteString
      getMakerBytes();

  /**
   * <code>optional string recordCompany = 74;</code>
   */
  java.lang.String getRecordCompany();
  /**
   * <code>optional string recordCompany = 74;</code>
   */
  com.google.protobuf.ByteString
      getRecordCompanyBytes();

  /**
   * <code>optional string copyrightCompany = 75;</code>
   */
  java.lang.String getCopyrightCompany();
  /**
   * <code>optional string copyrightCompany = 75;</code>
   */
  com.google.protobuf.ByteString
      getCopyrightCompanyBytes();

  /**
   * <code>optional string copyrightStart = 76;</code>
   */
  java.lang.String getCopyrightStart();
  /**
   * <code>optional string copyrightStart = 76;</code>
   */
  com.google.protobuf.ByteString
      getCopyrightStartBytes();

  /**
   * <code>optional string copyrightEnd = 77;</code>
   */
  java.lang.String getCopyrightEnd();
  /**
   * <code>optional string copyrightEnd = 77;</code>
   */
  com.google.protobuf.ByteString
      getCopyrightEndBytes();

  /**
   * <code>optional string copyrightType = 78;</code>
   */
  java.lang.String getCopyrightType();
  /**
   * <code>optional string copyrightType = 78;</code>
   */
  com.google.protobuf.ByteString
      getCopyrightTypeBytes();

  /**
   * <code>optional string copyrightTypeName = 79;</code>
   */
  java.lang.String getCopyrightTypeName();
  /**
   * <code>optional string copyrightTypeName = 79;</code>
   */
  com.google.protobuf.ByteString
      getCopyrightTypeNameBytes();

  /**
   * <code>optional string disableType = 80;</code>
   */
  java.lang.String getDisableType();
  /**
   * <code>optional string disableType = 80;</code>
   */
  com.google.protobuf.ByteString
      getDisableTypeBytes();

  /**
   * <code>optional string disableTypeName = 81;</code>
   */
  java.lang.String getDisableTypeName();
  /**
   * <code>optional string disableTypeName = 81;</code>
   */
  com.google.protobuf.ByteString
      getDisableTypeNameBytes();

  /**
   * <code>optional string issueCompany = 82;</code>
   */
  java.lang.String getIssueCompany();
  /**
   * <code>optional string issueCompany = 82;</code>
   */
  com.google.protobuf.ByteString
      getIssueCompanyBytes();

  /**
   * <code>optional string musicCompose = 83;</code>
   */
  java.lang.String getMusicCompose();
  /**
   * <code>optional string musicCompose = 83;</code>
   */
  com.google.protobuf.ByteString
      getMusicComposeBytes();

  /**
   * <code>optional string team = 84;</code>
   */
  java.lang.String getTeam();
  /**
   * <code>optional string team = 84;</code>
   */
  com.google.protobuf.ByteString
      getTeamBytes();

  /**
   * <code>optional string transCodePrefix = 85;</code>
   */
  java.lang.String getTransCodePrefix();
  /**
   * <code>optional string transCodePrefix = 85;</code>
   */
  com.google.protobuf.ByteString
      getTransCodePrefixBytes();

  /**
   * <code>optional string recreationType = 86;</code>
   */
  java.lang.String getRecreationType();
  /**
   * <code>optional string recreationType = 86;</code>
   */
  com.google.protobuf.ByteString
      getRecreationTypeBytes();

  /**
   * <code>optional string recreationTypeName = 87;</code>
   */
  java.lang.String getRecreationTypeName();
  /**
   * <code>optional string recreationTypeName = 87;</code>
   */
  com.google.protobuf.ByteString
      getRecreationTypeNameBytes();

  /**
   * <code>optional string playStreams = 88;</code>
   */
  java.lang.String getPlayStreams();
  /**
   * <code>optional string playStreams = 88;</code>
   */
  com.google.protobuf.ByteString
      getPlayStreamsBytes();

  /**
   * <code>optional string carfilmType = 89;</code>
   */
  java.lang.String getCarfilmType();
  /**
   * <code>optional string carfilmType = 89;</code>
   */
  com.google.protobuf.ByteString
      getCarfilmTypeBytes();

  /**
   * <code>optional string carfilmTypeName = 90;</code>
   */
  java.lang.String getCarfilmTypeName();
  /**
   * <code>optional string carfilmTypeName = 90;</code>
   */
  com.google.protobuf.ByteString
      getCarfilmTypeNameBytes();

  /**
   * <code>optional int64 createTime = 91;</code>
   */
  long getCreateTime();

  /**
   * <code>optional int64 updateTime = 92;</code>
   */
  long getUpdateTime();

  /**
   * <code>optional string midStreams = 93;</code>
   */
  java.lang.String getMidStreams();
  /**
   * <code>optional string midStreams = 93;</code>
   */
  com.google.protobuf.ByteString
      getMidStreamsBytes();

  /**
   * <code>optional int32 attr = 94;</code>
   */
  int getAttr();

  /**
   * <code>optional int32 logonum = 95;</code>
   */
  int getLogonum();

  /**
   * <code>optional string drmFlagId = 96;</code>
   */
  java.lang.String getDrmFlagId();
  /**
   * <code>optional string drmFlagId = 96;</code>
   */
  com.google.protobuf.ByteString
      getDrmFlagIdBytes();

  /**
   * <code>optional string pic = 97;</code>
   */
  java.lang.String getPic();
  /**
   * <code>optional string pic = 97;</code>
   */
  com.google.protobuf.ByteString
      getPicBytes();

  /**
   * <code>optional int32 isPlayLock = 98;</code>
   */
  int getIsPlayLock();

  /**
   * <code>optional int32 ismobile = 99;</code>
   */
  int getIsmobile();

  /**
   * <code>optional int64 vv = 100;</code>
   */
  long getVv();

  /**
   * <code>optional int64 commentCnt = 101;</code>
   */
  long getCommentCnt();

  /**
   * <code>repeated string videoStreams = 102;</code>
   */
  java.util.List<java.lang.String>
      getVideoStreamsList();
  /**
   * <code>repeated string videoStreams = 102;</code>
   */
  int getVideoStreamsCount();
  /**
   * <code>repeated string videoStreams = 102;</code>
   */
  java.lang.String getVideoStreams(int index);
  /**
   * <code>repeated string videoStreams = 102;</code>
   */
  com.google.protobuf.ByteString
      getVideoStreamsBytes(int index);

  /**
   * <code>optional int64 midL = 103;</code>
   */
  long getMidL();

  /**
   * <code>repeated .Stream streams = 104;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getStreamsList();
  /**
   * <code>repeated .Stream streams = 104;</code>
   */
  grpc.videoservice.Stream getStreams(int index);
  /**
   * <code>repeated .Stream streams = 104;</code>
   */
  int getStreamsCount();
  /**
   * <code>repeated .Stream streams = 104;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getStreamsOrBuilderList();
  /**
   * <code>repeated .Stream streams = 104;</code>
   */
  grpc.videoservice.StreamOrBuilder getStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream normalStreams = 105;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getNormalStreamsList();
  /**
   * <code>repeated .Stream normalStreams = 105;</code>
   */
  grpc.videoservice.Stream getNormalStreams(int index);
  /**
   * <code>repeated .Stream normalStreams = 105;</code>
   */
  int getNormalStreamsCount();
  /**
   * <code>repeated .Stream normalStreams = 105;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getNormalStreamsOrBuilderList();
  /**
   * <code>repeated .Stream normalStreams = 105;</code>
   */
  grpc.videoservice.StreamOrBuilder getNormalStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream theatreStreams = 106;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getTheatreStreamsList();
  /**
   * <code>repeated .Stream theatreStreams = 106;</code>
   */
  grpc.videoservice.Stream getTheatreStreams(int index);
  /**
   * <code>repeated .Stream theatreStreams = 106;</code>
   */
  int getTheatreStreamsCount();
  /**
   * <code>repeated .Stream theatreStreams = 106;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getTheatreStreamsOrBuilderList();
  /**
   * <code>repeated .Stream theatreStreams = 106;</code>
   */
  grpc.videoservice.StreamOrBuilder getTheatreStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream threeDStreams = 107;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getThreeDStreamsList();
  /**
   * <code>repeated .Stream threeDStreams = 107;</code>
   */
  grpc.videoservice.Stream getThreeDStreams(int index);
  /**
   * <code>repeated .Stream threeDStreams = 107;</code>
   */
  int getThreeDStreamsCount();
  /**
   * <code>repeated .Stream threeDStreams = 107;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getThreeDStreamsOrBuilderList();
  /**
   * <code>repeated .Stream threeDStreams = 107;</code>
   */
  grpc.videoservice.StreamOrBuilder getThreeDStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream dolbyStreams = 108;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getDolbyStreamsList();
  /**
   * <code>repeated .Stream dolbyStreams = 108;</code>
   */
  grpc.videoservice.Stream getDolbyStreams(int index);
  /**
   * <code>repeated .Stream dolbyStreams = 108;</code>
   */
  int getDolbyStreamsCount();
  /**
   * <code>repeated .Stream dolbyStreams = 108;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getDolbyStreamsOrBuilderList();
  /**
   * <code>repeated .Stream dolbyStreams = 108;</code>
   */
  grpc.videoservice.StreamOrBuilder getDolbyStreamsOrBuilder(
      int index);

  /**
   * <code>repeated .Stream dtsStreams = 109;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getDtsStreamsList();
  /**
   * <code>repeated .Stream dtsStreams = 109;</code>
   */
  grpc.videoservice.Stream getDtsStreams(int index);
  /**
   * <code>repeated .Stream dtsStreams = 109;</code>
   */
  int getDtsStreamsCount();
  /**
   * <code>repeated .Stream dtsStreams = 109;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getDtsStreamsOrBuilderList();
  /**
   * <code>repeated .Stream dtsStreams = 109;</code>
   */
  grpc.videoservice.StreamOrBuilder getDtsStreamsOrBuilder(
      int index);

  /**
   * <code>optional int32 page = 110;</code>
   */
  int getPage();

  /**
   * <code>repeated .ActorCache guestList = 111;</code>
   */
  java.util.List<grpc.videoservice.ActorCache> 
      getGuestListList();
  /**
   * <code>repeated .ActorCache guestList = 111;</code>
   */
  grpc.videoservice.ActorCache getGuestList(int index);
  /**
   * <code>repeated .ActorCache guestList = 111;</code>
   */
  int getGuestListCount();
  /**
   * <code>repeated .ActorCache guestList = 111;</code>
   */
  java.util.List<? extends grpc.videoservice.ActorCacheOrBuilder> 
      getGuestListOrBuilderList();
  /**
   * <code>repeated .ActorCache guestList = 111;</code>
   */
  grpc.videoservice.ActorCacheOrBuilder getGuestListOrBuilder(
      int index);

  /**
   * <code>repeated int64 segmentIds = 112;</code>
   */
  java.util.List<java.lang.Long> getSegmentIdsList();
  /**
   * <code>repeated int64 segmentIds = 112;</code>
   */
  int getSegmentIdsCount();
  /**
   * <code>repeated int64 segmentIds = 112;</code>
   */
  long getSegmentIds(int index);

  /**
   * <code>optional int32 isDanmaku = 113;</code>
   */
  int getIsDanmaku();

  /**
   * <code>repeated int64 guestIds = 114;</code>
   */
  java.util.List<java.lang.Long> getGuestIdsList();
  /**
   * <code>repeated int64 guestIds = 114;</code>
   */
  int getGuestIdsCount();
  /**
   * <code>repeated int64 guestIds = 114;</code>
   */
  long getGuestIds(int index);

  /**
   * <code>repeated .Stream VRstreams = 115;</code>
   */
  java.util.List<grpc.videoservice.Stream> 
      getVRstreamsList();
  /**
   * <code>repeated .Stream VRstreams = 115;</code>
   */
  grpc.videoservice.Stream getVRstreams(int index);
  /**
   * <code>repeated .Stream VRstreams = 115;</code>
   */
  int getVRstreamsCount();
  /**
   * <code>repeated .Stream VRstreams = 115;</code>
   */
  java.util.List<? extends grpc.videoservice.StreamOrBuilder> 
      getVRstreamsOrBuilderList();
  /**
   * <code>repeated .Stream VRstreams = 115;</code>
   */
  grpc.videoservice.StreamOrBuilder getVRstreamsOrBuilder(
      int index);

  /**
   * <code>optional string vtypeFlag = 116;</code>
   */
  java.lang.String getVtypeFlag();
  /**
   * <code>optional string vtypeFlag = 116;</code>
   */
  com.google.protobuf.ByteString
      getVtypeFlagBytes();

  /**
   * <code>optional string allStreams = 117;</code>
   */
  java.lang.String getAllStreams();
  /**
   * <code>optional string allStreams = 117;</code>
   */
  com.google.protobuf.ByteString
      getAllStreamsBytes();

  /**
   * <code>optional string contentRatingId = 118;</code>
   */
  java.lang.String getContentRatingId();
  /**
   * <code>optional string contentRatingId = 118;</code>
   */
  com.google.protobuf.ByteString
      getContentRatingIdBytes();

  /**
   * <code>optional string contentRatingValue = 119;</code>
   */
  java.lang.String getContentRatingValue();
  /**
   * <code>optional string contentRatingValue = 119;</code>
   */
  com.google.protobuf.ByteString
      getContentRatingValueBytes();

  /**
   * <code>optional string coopPlatform = 120;</code>
   */
  java.lang.String getCoopPlatform();
  /**
   * <code>optional string coopPlatform = 120;</code>
   */
  com.google.protobuf.ByteString
      getCoopPlatformBytes();

  /**
   * <code>optional string statusCode = 121;</code>
   */
  java.lang.String getStatusCode();
  /**
   * <code>optional string statusCode = 121;</code>
   */
  com.google.protobuf.ByteString
      getStatusCodeBytes();
}
