// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

/**
 * Protobuf type {@code Videos}
 */
public  final class Videos extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Videos)
    VideosOrBuilder {
  // Use Videos.newBuilder() to construct.
  private Videos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Videos() {
    videos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Videos(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              videos_ = new java.util.ArrayList<grpc.videoservice.Video>();
              mutable_bitField0_ |= 0x00000001;
            }
            videos_.add(
                input.readMessage(grpc.videoservice.Video.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        videos_ = java.util.Collections.unmodifiableList(videos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.videoservice.VideoServiceProto.internal_static_Videos_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.videoservice.VideoServiceProto.internal_static_Videos_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.videoservice.Videos.class, grpc.videoservice.Videos.Builder.class);
  }

  public static final int VIDEOS_FIELD_NUMBER = 1;
  private java.util.List<grpc.videoservice.Video> videos_;
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  public java.util.List<grpc.videoservice.Video> getVideosList() {
    return videos_;
  }
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  public java.util.List<? extends grpc.videoservice.VideoOrBuilder> 
      getVideosOrBuilderList() {
    return videos_;
  }
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  public int getVideosCount() {
    return videos_.size();
  }
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  public grpc.videoservice.Video getVideos(int index) {
    return videos_.get(index);
  }
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  public grpc.videoservice.VideoOrBuilder getVideosOrBuilder(
      int index) {
    return videos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < videos_.size(); i++) {
      output.writeMessage(1, videos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < videos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, videos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.videoservice.Videos)) {
      return super.equals(obj);
    }
    grpc.videoservice.Videos other = (grpc.videoservice.Videos) obj;

    boolean result = true;
    result = result && getVideosList()
        .equals(other.getVideosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getVideosCount() > 0) {
      hash = (37 * hash) + VIDEOS_FIELD_NUMBER;
      hash = (53 * hash) + getVideosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.videoservice.Videos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.Videos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.Videos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.videoservice.Videos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.videoservice.Videos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Videos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.Videos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Videos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.videoservice.Videos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.videoservice.Videos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.videoservice.Videos prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Videos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Videos)
      grpc.videoservice.VideosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.videoservice.VideoServiceProto.internal_static_Videos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.videoservice.VideoServiceProto.internal_static_Videos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.videoservice.Videos.class, grpc.videoservice.Videos.Builder.class);
    }

    // Construct using grpc.videoservice.Videos.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVideosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (videosBuilder_ == null) {
        videos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        videosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.videoservice.VideoServiceProto.internal_static_Videos_descriptor;
    }

    public grpc.videoservice.Videos getDefaultInstanceForType() {
      return grpc.videoservice.Videos.getDefaultInstance();
    }

    public grpc.videoservice.Videos build() {
      grpc.videoservice.Videos result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.videoservice.Videos buildPartial() {
      grpc.videoservice.Videos result = new grpc.videoservice.Videos(this);
      int from_bitField0_ = bitField0_;
      if (videosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          videos_ = java.util.Collections.unmodifiableList(videos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.videos_ = videos_;
      } else {
        result.videos_ = videosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.videoservice.Videos) {
        return mergeFrom((grpc.videoservice.Videos)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.videoservice.Videos other) {
      if (other == grpc.videoservice.Videos.getDefaultInstance()) return this;
      if (videosBuilder_ == null) {
        if (!other.videos_.isEmpty()) {
          if (videos_.isEmpty()) {
            videos_ = other.videos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVideosIsMutable();
            videos_.addAll(other.videos_);
          }
          onChanged();
        }
      } else {
        if (!other.videos_.isEmpty()) {
          if (videosBuilder_.isEmpty()) {
            videosBuilder_.dispose();
            videosBuilder_ = null;
            videos_ = other.videos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            videosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVideosFieldBuilder() : null;
          } else {
            videosBuilder_.addAllMessages(other.videos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.videoservice.Videos parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.videoservice.Videos) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.videoservice.Video> videos_ =
      java.util.Collections.emptyList();
    private void ensureVideosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        videos_ = new java.util.ArrayList<grpc.videoservice.Video>(videos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Video, grpc.videoservice.Video.Builder, grpc.videoservice.VideoOrBuilder> videosBuilder_;

    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public java.util.List<grpc.videoservice.Video> getVideosList() {
      if (videosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(videos_);
      } else {
        return videosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public int getVideosCount() {
      if (videosBuilder_ == null) {
        return videos_.size();
      } else {
        return videosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public grpc.videoservice.Video getVideos(int index) {
      if (videosBuilder_ == null) {
        return videos_.get(index);
      } else {
        return videosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder setVideos(
        int index, grpc.videoservice.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.set(index, value);
        onChanged();
      } else {
        videosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder setVideos(
        int index, grpc.videoservice.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.set(index, builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder addVideos(grpc.videoservice.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.add(value);
        onChanged();
      } else {
        videosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder addVideos(
        int index, grpc.videoservice.Video value) {
      if (videosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVideosIsMutable();
        videos_.add(index, value);
        onChanged();
      } else {
        videosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder addVideos(
        grpc.videoservice.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.add(builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder addVideos(
        int index, grpc.videoservice.Video.Builder builderForValue) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.add(index, builderForValue.build());
        onChanged();
      } else {
        videosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder addAllVideos(
        java.lang.Iterable<? extends grpc.videoservice.Video> values) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, videos_);
        onChanged();
      } else {
        videosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder clearVideos() {
      if (videosBuilder_ == null) {
        videos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        videosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public Builder removeVideos(int index) {
      if (videosBuilder_ == null) {
        ensureVideosIsMutable();
        videos_.remove(index);
        onChanged();
      } else {
        videosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public grpc.videoservice.Video.Builder getVideosBuilder(
        int index) {
      return getVideosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public grpc.videoservice.VideoOrBuilder getVideosOrBuilder(
        int index) {
      if (videosBuilder_ == null) {
        return videos_.get(index);  } else {
        return videosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public java.util.List<? extends grpc.videoservice.VideoOrBuilder> 
         getVideosOrBuilderList() {
      if (videosBuilder_ != null) {
        return videosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(videos_);
      }
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public grpc.videoservice.Video.Builder addVideosBuilder() {
      return getVideosFieldBuilder().addBuilder(
          grpc.videoservice.Video.getDefaultInstance());
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public grpc.videoservice.Video.Builder addVideosBuilder(
        int index) {
      return getVideosFieldBuilder().addBuilder(
          index, grpc.videoservice.Video.getDefaultInstance());
    }
    /**
     * <code>repeated .Video videos = 1;</code>
     */
    public java.util.List<grpc.videoservice.Video.Builder> 
         getVideosBuilderList() {
      return getVideosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.videoservice.Video, grpc.videoservice.Video.Builder, grpc.videoservice.VideoOrBuilder> 
        getVideosFieldBuilder() {
      if (videosBuilder_ == null) {
        videosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.videoservice.Video, grpc.videoservice.Video.Builder, grpc.videoservice.VideoOrBuilder>(
                videos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        videos_ = null;
      }
      return videosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Videos)
  }

  // @@protoc_insertion_point(class_scope:Videos)
  private static final grpc.videoservice.Videos DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.videoservice.Videos();
  }

  public static grpc.videoservice.Videos getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Videos>
      PARSER = new com.google.protobuf.AbstractParser<Videos>() {
    public Videos parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Videos(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Videos> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Videos> getParserForType() {
    return PARSER;
  }

  public grpc.videoservice.Videos getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

