// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface VideoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();
}
