// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface VideoIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string id = 1;</code>
   */
  java.util.List<java.lang.String>
      getIdList();
  /**
   * <code>repeated string id = 1;</code>
   */
  int getIdCount();
  /**
   * <code>repeated string id = 1;</code>
   */
  java.lang.String getId(int index);
  /**
   * <code>repeated string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes(int index);
}
