// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface VideosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Videos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Video videos = 1;</code>
   */
  java.util.List<grpc.videoservice.Video> 
      getVideosList();
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  grpc.videoservice.Video getVideos(int index);
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  int getVideosCount();
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  java.util.List<? extends grpc.videoservice.VideoOrBuilder> 
      getVideosOrBuilderList();
  /**
   * <code>repeated .Video videos = 1;</code>
   */
  grpc.videoservice.VideoOrBuilder getVideosOrBuilder(
      int index);
}
