// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public final class VideoServiceProto {
  private VideoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WatchingFocusCache_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WatchingFocusCache_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PicAll_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PicAll_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActorCache_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActorCache_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Videos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Videos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022videoservice.proto\"\032\n\014VideoRequest\022\n\n\002" +
      "id\030\001 \001(\003\"\325\023\n\005Video\022\017\n\007albumId\030\001 \001(\003\022\n\n\002i" +
      "d\030\002 \001(\003\022\014\n\004type\030\003 \001(\005\022\016\n\006porder\030\004 \001(\005\022\013\n" +
      "\003mid\030\005 \001(\t\022\016\n\006nameCn\030\006 \001(\t\022\r\n\005alias\030\007 \001(" +
      "\t\022\020\n\010subTitle\030\010 \001(\t\022\021\n\tshortDesc\030\t \001(\t\022\023" +
      "\n\013description\030\n \001(\t\022\013\n\003tag\030\013 \001(\t\022\022\n\ncate" +
      "goryId\030\014 \001(\005\022\024\n\014categoryName\030\r \001(\t\022\023\n\013su" +
      "bCategory\030\016 \001(\t\022\027\n\017subCategoryName\030\017 \001(\t" +
      "\022\014\n\004area\030\020 \001(\t\022\020\n\010areaName\030\021 \001(\t\022\017\n\007epis" +
      "ode\030\022 \001(\t\022\r\n\005btime\030\023 \001(\005\022\r\n\005etime\030\024 \001(\005\022",
      "*\n\rwatchingFocus\030\025 \003(\0132\023.WatchingFocusCa" +
      "che\022\030\n\020downloadPlatform\030\026 \001(\t\022\024\n\014playPla" +
      "tform\030\027 \001(\t\022\023\n\013payPlatform\030\030 \001(\t\022\020\n\010dura" +
      "tion\030\031 \001(\005\022\016\n\006status\030\032 \001(\005\022\017\n\007deleted\030\033 " +
      "\001(\005\022\016\n\006remark\030\034 \001(\t\022\r\n\005score\030\035 \001(\002\022\027\n\006pi" +
      "cAll\030\036 \003(\0132\007.PicAll\022\023\n\013picOriginal\030\037 \001(\t" +
      "\022\027\n\017relativeContent\030  \001(\t\022\023\n\013releaseDate" +
      "\030! \001(\t\022\025\n\rfirstPlayTime\030\" \001(\t\022\r\n\005issue\030#" +
      " \001(\005\022\016\n\006school\030$ \001(\t\022\020\n\010starring\030% \001(\t\022\021" +
      "\n\tdirectory\030& \001(\t\022\r\n\005actor\030\' \001(\t\022\021\n\tacto",
      "rPlay\030( \001(\t\022\020\n\010language\030) \001(\005\022\024\n\014languag" +
      "eName\030* \001(\t\022\022\n\nsingleName\030+ \001(\t\022\r\n\005style" +
      "\030, \001(\005\022\021\n\tstyleName\030- \001(\t\022\022\n\nsportsType\030" +
      ". \001(\005\022\026\n\016sportsTypeName\030/ \001(\t\022\025\n\rletvMak" +
      "eStyle\0300 \001(\005\022\031\n\021letvMakeStyleName\0301 \001(\t\022" +
      "\020\n\010popStyle\0302 \001(\005\022\024\n\014popStyleName\0303 \001(\t\022" +
      "\030\n\020letvProduceStyle\0304 \001(\005\022\034\n\024letvProduce" +
      "StyleName\0305 \001(\t\022\024\n\014cartoonStyle\0306 \001(\t\022\030\n" +
      "\020cartoonStyleName\0307 \001(\t\022\021\n\tfieldType\0308 \001" +
      "(\005\022\025\n\rfieldTypeName\0309 \001(\t\022\013\n\003pre\030: \001(\005\022\017",
      "\n\007preName\030; \001(\t\022\022\n\ninstructor\030< \001(\t\022\017\n\007c" +
      "ompere\030= \001(\t\022\r\n\005guest\030> \001(\t\022\016\n\006singer\030? " +
      "\001(\t\022\022\n\nsingerType\030@ \001(\t\022\026\n\016singerTypeNam" +
      "e\030A \001(\t\022\024\n\014musicAuthors\030B \001(\t\022\022\n\nmusicSt" +
      "yle\030C \001(\t\022\026\n\016musicStyleName\030D \001(\t\022\023\n\013tra" +
      "velTheme\030E \001(\005\022\027\n\017travelThemeName\030F \001(\t\022" +
      "\022\n\ntravelType\030G \001(\005\022\026\n\016travelTypeName\030H " +
      "\001(\t\022\r\n\005maker\030I \001(\t\022\025\n\rrecordCompany\030J \001(" +
      "\t\022\030\n\020copyrightCompany\030K \001(\t\022\026\n\016copyright" +
      "Start\030L \001(\t\022\024\n\014copyrightEnd\030M \001(\t\022\025\n\rcop",
      "yrightType\030N \001(\t\022\031\n\021copyrightTypeName\030O " +
      "\001(\t\022\023\n\013disableType\030P \001(\t\022\027\n\017disableTypeN" +
      "ame\030Q \001(\t\022\024\n\014issueCompany\030R \001(\t\022\024\n\014music" +
      "Compose\030S \001(\t\022\014\n\004team\030T \001(\t\022\027\n\017transCode" +
      "Prefix\030U \001(\t\022\026\n\016recreationType\030V \001(\t\022\032\n\022" +
      "recreationTypeName\030W \001(\t\022\023\n\013playStreams\030" +
      "X \001(\t\022\023\n\013carfilmType\030Y \001(\t\022\027\n\017carfilmTyp" +
      "eName\030Z \001(\t\022\022\n\ncreateTime\030[ \001(\003\022\022\n\nupdat" +
      "eTime\030\\ \001(\003\022\022\n\nmidStreams\030] \001(\t\022\014\n\004attr\030" +
      "^ \001(\005\022\017\n\007logonum\030_ \001(\005\022\021\n\tdrmFlagId\030` \001(",
      "\t\022\013\n\003pic\030a \001(\t\022\022\n\nisPlayLock\030b \001(\005\022\020\n\010is" +
      "mobile\030c \001(\005\022\n\n\002vv\030d \001(\003\022\022\n\ncommentCnt\030e" +
      " \001(\003\022\024\n\014videoStreams\030f \003(\t\022\014\n\004midL\030g \001(\003" +
      "\022\030\n\007streams\030h \003(\0132\007.Stream\022\036\n\rnormalStre" +
      "ams\030i \003(\0132\007.Stream\022\037\n\016theatreStreams\030j \003" +
      "(\0132\007.Stream\022\036\n\rthreeDStreams\030k \003(\0132\007.Str" +
      "eam\022\035\n\014dolbyStreams\030l \003(\0132\007.Stream\022\033\n\ndt" +
      "sStreams\030m \003(\0132\007.Stream\022\014\n\004page\030n \001(\005\022\036\n" +
      "\tguestList\030o \003(\0132\013.ActorCache\022\022\n\nsegment" +
      "Ids\030p \003(\003\022\021\n\tisDanmaku\030q \001(\005\022\020\n\010guestIds",
      "\030r \003(\003\022\032\n\tVRstreams\030s \003(\0132\007.Stream\022\021\n\tvt" +
      "ypeFlag\030t \001(\t\022\022\n\nallStreams\030u \001(\t\022\027\n\017con" +
      "tentRatingId\030v \001(\t\022\032\n\022contentRatingValue" +
      "\030w \001(\t\022\024\n\014coopPlatform\030x \001(\t\022\022\n\nstatusCo" +
      "de\030y \001(\t\"<\n\022WatchingFocusCache\022\014\n\004desc\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004time\030\003 \001(\003\"*\n\006PicAll" +
      "\022\016\n\006picKey\030\001 \001(\t\022\020\n\010picValue\030\002 \001(\t\"\332\001\n\006S" +
      "tream\022\014\n\004name\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\017\n\007can" +
      "Play\030\003 \001(\t\022\017\n\007canDown\030\004 \001(\t\022\014\n\004kbps\030\005 \001(" +
      "\t\022\021\n\tbandWidth\030\006 \001(\t\022\021\n\tisDefault\030\007 \001(\010\022",
      "\020\n\010fileSize\030\010 \001(\003\022\020\n\010ifCharge\030\t \001(\005\022\034\n\013l" +
      "iveStreams\030\n \003(\0132\007.Stream\022\034\n\013playStreams" +
      "\030\013 \003(\0132\007.Stream\"O\n\nActorCache\022\n\n\002id\030\001 \001(" +
      "\005\022\014\n\004name\030\002 \001(\t\022\014\n\004role\030\003 \001(\005\022\013\n\003img\030\004 \001" +
      "(\t\022\014\n\004type\030\005 \001(\005\"\035\n\017VideoIdsRequest\022\n\n\002i" +
      "d\030\001 \003(\t\" \n\006Videos\022\026\n\006videos\030\001 \003(\0132\006.Vide" +
      "o2\304\001\n\014VideoService\022#\n\010getVideo\022\r.VideoRe" +
      "quest\032\006.Video\"\000\022)\n\nmgetVideos\022\020.VideoIds" +
      "Request\032\007.Videos\"\000\0222\n\022mgetVideosByStream" +
      "\022\020.VideoIdsRequest\032\006.Video\"\0000\001\0220\n\021getVid",
      "eosByStream\022\r.VideoRequest\032\006.Video\"\000(\0010\001" +
      "B(\n\021grpc.videoserviceB\021VideoServiceProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VideoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VideoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Video_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Video_descriptor,
        new java.lang.String[] { "AlbumId", "Id", "Type", "Porder", "Mid", "NameCn", "Alias", "SubTitle", "ShortDesc", "Description", "Tag", "CategoryId", "CategoryName", "SubCategory", "SubCategoryName", "Area", "AreaName", "Episode", "Btime", "Etime", "WatchingFocus", "DownloadPlatform", "PlayPlatform", "PayPlatform", "Duration", "Status", "Deleted", "Remark", "Score", "PicAll", "PicOriginal", "RelativeContent", "ReleaseDate", "FirstPlayTime", "Issue", "School", "Starring", "Directory", "Actor", "ActorPlay", "Language", "LanguageName", "SingleName", "Style", "StyleName", "SportsType", "SportsTypeName", "LetvMakeStyle", "LetvMakeStyleName", "PopStyle", "PopStyleName", "LetvProduceStyle", "LetvProduceStyleName", "CartoonStyle", "CartoonStyleName", "FieldType", "FieldTypeName", "Pre", "PreName", "Instructor", "Compere", "Guest", "Singer", "SingerType", "SingerTypeName", "MusicAuthors", "MusicStyle", "MusicStyleName", "TravelTheme", "TravelThemeName", "TravelType", "TravelTypeName", "Maker", "RecordCompany", "CopyrightCompany", "CopyrightStart", "CopyrightEnd", "CopyrightType", "CopyrightTypeName", "DisableType", "DisableTypeName", "IssueCompany", "MusicCompose", "Team", "TransCodePrefix", "RecreationType", "RecreationTypeName", "PlayStreams", "CarfilmType", "CarfilmTypeName", "CreateTime", "UpdateTime", "MidStreams", "Attr", "Logonum", "DrmFlagId", "Pic", "IsPlayLock", "Ismobile", "Vv", "CommentCnt", "VideoStreams", "MidL", "Streams", "NormalStreams", "TheatreStreams", "ThreeDStreams", "DolbyStreams", "DtsStreams", "Page", "GuestList", "SegmentIds", "IsDanmaku", "GuestIds", "VRstreams", "VtypeFlag", "AllStreams", "ContentRatingId", "ContentRatingValue", "CoopPlatform", "StatusCode", });
    internal_static_WatchingFocusCache_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WatchingFocusCache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WatchingFocusCache_descriptor,
        new java.lang.String[] { "Desc", "Id", "Time", });
    internal_static_PicAll_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PicAll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PicAll_descriptor,
        new java.lang.String[] { "PicKey", "PicValue", });
    internal_static_Stream_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Stream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stream_descriptor,
        new java.lang.String[] { "Name", "Code", "CanPlay", "CanDown", "Kbps", "BandWidth", "IsDefault", "FileSize", "IfCharge", "LiveStreams", "PlayStreams", });
    internal_static_ActorCache_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ActorCache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActorCache_descriptor,
        new java.lang.String[] { "Id", "Name", "Role", "Img", "Type", });
    internal_static_VideoIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_VideoIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoIdsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Videos_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Videos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Videos_descriptor,
        new java.lang.String[] { "Videos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
