// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: videoservice.proto

package grpc.videoservice;

public interface WatchingFocusCacheOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WatchingFocusCache)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string desc = 1;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 1;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional int64 time = 3;</code>
   */
  long getTime();
}
